apiVersion: v1
kind: Service
metadata:
  name: platform-cedar-sidecar
  namespace: platform
spec:
  selector:
    app: platform-cedar-sidecar
  ports:
    - name: http
      port: 80
      targetPort: 8080
